### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.flurry.android.FlurryUnityApplication

### ISSUE THREAD

**Issue by amit232git** [Majchrzak/Flurry-Unity-3D#19]
Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.flurry.android.FlurryUnityApplication
    java.lang.ClassNotFoundException: com.flurry.android.FlurryUnityApplication
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
        at android.os.MessageQueue.next(MessageQueue.java:392)
        at android.os.Looper.loop(Looper.java:136)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.flurry.android.FlurryUnityApplication" on path: DexPathList[[zip file "/data/app/com.macrobian.ultishooter-1/base.apk"],nativeLibraryDirectories=[/data/app/com.macrobian.ultishooter-1/lib/arm, /data/app/com.macrobian.ultishooter-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
    	at dalvik.system.Base

**Comment by joshalanwagner** [comment]
I'm seeing a similar error in Unity 2019. 
java.lang.ClassNotFoundException: com.flurry.android.FlurryAgent$Builder
java.lang.ClassNotFoundException: com.flurry.android.FlurryAgent
